import {
  IconBan,
  IconBlur,
  IconCheckFilled,
  IconCircle,
  IconCircleArrowRight,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleDashed,
  IconCircleDotted,
  IconCircleMinus,
  IconClockPause,
  IconNoiseReduction,
  IconPackage,
  IconPacman,
  IconPacmanFilled,
  IconPoint,
  IconProgress,
} from '@tabler/icons-react';

export const statusIcons = {
  backlog: IconCircleDashed,
  'to do': IconCircleDashed,
  scoping: IconCircleDotted,
  'in review': IconNoiseReduction,
  'in design': IconProgress,
  'in progress': IconCircle,
  'in development': IconCircle,
  testing: IconBlur,
  waiting: IconClockPause,
  blocked: IconBan,
  'ready for development': IconPacman,
  ready: IconCircleCheckFilled,
  shipped: IconCircleCheckFilled,
  complete: IconCircleCheckFilled,
  cancelled: IconCircleCheck,
};
