/**
 * full-reset.ts
 *
 * Wipes ALL OpenProject data (projects, work packages, imported users, groups, API tokens)
 * and ALL relevant Prisma data, then re-runs setup and seed from scratch.
 *
 * Uses docker exec Rails runner for OP operations — bypasses the API limitations
 * (background-job deletions, 403 on user/status endpoints, etc.).
 *
 * Usage:
 *   npx tsx scripts/full-reset.ts [--container <name>] [--skip-seed]
 */
import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { seededHierarchyPath } from '../server/openproject/hierarchyStore.js';
import { execSync, spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { unlink } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// ─── helpers ─────────────────────────────────────────────────────────────────

function step(msg: string) {
  console.log(`\n\x1b[36m→\x1b[0m ${msg}`);
}
function ok(msg: string) {
  console.log(`  \x1b[32m✓\x1b[0m ${msg}`);
}
function warn(msg: string) {
  console.warn(`  \x1b[33m⚠\x1b[0m ${msg}`);
}
function fail(msg: string): never {
  console.error(`\n\x1b[31m✗\x1b[0m ${msg}\n`);
  process.exit(1);
}

function parseArgs() {
  const argv = process.argv.slice(2);
  const containerIdx = argv.indexOf('--container');
  return {
    container: containerIdx >= 0 ? argv[containerIdx + 1] : 'openproject-web-1',
    skipSeed: argv.includes('--skip-seed'),
    skipSetup: argv.includes('--skip-setup'),
  };
}

// ─── Rails runner helper ─────────────────────────────────────────────────────

function rails(container: string, script: string, label: string): string {
  step(label);
  try {
    const out = execSync(`docker exec ${container} bundle exec rails runner '${script}'`, {
      timeout: 180_000,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return out;
  } catch (error: any) {
    const msg = (error?.stderr || error?.stdout || error?.message || String(error)).slice(0, 600);
    warn(`Rails runner failed: ${msg}`);
    return '';
  }
}

// ─── OpenProject nuking via Rails ────────────────────────────────────────────

async function nukeOpenProject(container: string) {
  // 1. Delete all work packages first (avoids FK issues)
  const wpOut = rails(
    container,
    'n=WorkPackage.delete_all; puts "WP_DELETED:"+n.to_s',
    'Deleting all work packages (Rails)'
  );
  const wpMatch = wpOut.match(/WP_DELETED:(\d+)/);
  if (wpMatch) ok(`Deleted ${wpMatch[1]} work packages`);

  // 2. Delete all journals (can block project deletion)
  rails(
    container,
    'Journal.delete_all; JournalManager.send(:journal_class_name, WorkPackage) rescue nil; puts "Journals cleared"',
    'Clearing journals'
  );

  // 3. Destroy all projects (destroy not delete — triggers callbacks that clean child records)
  const projOut = rails(
    container,
    'n=0; Project.all.each { |p| p.destroy; n+=1 }; puts "PROJ_DELETED:"+n.to_s',
    'Destroying all projects (Rails)'
  );
  const projMatch = projOut.match(/PROJ_DELETED:(\d+)/);
  if (projMatch) ok(`Destroyed ${projMatch[1]} projects`);

  // 4. Force-destroy any archived projects that survived the above
  const archOut = rails(
    container,
    'remaining=Project.count; Project.delete_all; puts "ARCH_DELETED:"+remaining.to_s',
    'Force-deleting remaining archived projects'
  );
  const archMatch = archOut.match(/ARCH_DELETED:(\d+)/);
  if (archMatch && archMatch[1] !== '0') {
    ok(`Force-deleted ${archMatch[1]} remaining project rows`);
  }

  // 5. Delete imported (non-admin, non-system) users
  const usersOut = rails(
    container,
    [
      'skip=["AnonymousUser","DeletedUser","SystemUser"];',
      'n=0;',
      'User.where(admin:false).where.not(type:skip).each { |u| u.destroy; n+=1 };',
      'puts "USERS_DELETED:"+n.to_s',
    ].join(''),
    'Deleting imported users (Rails)'
  );
  const usersMatch = usersOut.match(/USERS_DELETED:(\d+)/);
  if (usersMatch) ok(`Deleted ${usersMatch[1]} users`);

  // 6. Delete all groups
  const groupsOut = rails(
    container,
    'n=Group.count; Group.destroy_all; puts "GROUPS_DELETED:"+n.to_s',
    'Deleting all groups (Rails)'
  );
  const groupsMatch = groupsOut.match(/GROUPS_DELETED:(\d+)/);
  if (groupsMatch) ok(`Deleted ${groupsMatch[1]} groups`);

  // 7. Delete all API tokens for imported users (admin tokens are regenerated by setup)
  rails(container, 'Token::API.delete_all; puts "API tokens cleared"', 'Clearing API tokens');

  // 8. Final verification
  const verifyOut = rails(
    container,
    [
      'puts "VERIFY projects:"+Project.count.to_s;',
      'puts "VERIFY users:"+User.where(admin:false).where.not(type:["AnonymousUser","DeletedUser","SystemUser"]).count.to_s;',
      'puts "VERIFY groups:"+Group.count.to_s;',
      'puts "VERIFY wps:"+WorkPackage.count.to_s',
    ].join(''),
    'Verifying OpenProject state'
  );
  for (const line of verifyOut.split('\n')) {
    const m = line.match(/^VERIFY (.+):(\d+)$/);
    if (m) ok(`${m[1]}: ${m[2]} remaining`);
  }
}

// ─── Prisma nuking ────────────────────────────────────────────────────────────

async function nukePrisma() {
  step('Cleaning Prisma data');
  const prisma = new PrismaClient();

  try {
    // Delete in dependency order (children before parents)
    const counts = await prisma.$transaction([
      prisma.taskGitHubLink.deleteMany(),
      prisma.gitHubCommit.deleteMany(),
      prisma.gitHubBranch.deleteMany(),
      prisma.gitHubPullRequest.deleteMany(),
      prisma.gitHubRepository.deleteMany(),
      prisma.githubIntegration.deleteMany(),
      prisma.taskDependency.deleteMany(),
      prisma.taskComment.deleteMany(),
      prisma.taskTag.deleteMany(),
      prisma.openProjectWorkPackageTag.deleteMany(),
      prisma.checklistItem.deleteMany(),
      prisma.checklist.deleteMany(),
      prisma.activityLog.deleteMany(),
      prisma.notification.deleteMany(),
      prisma.openProjectBoardCardOrder.deleteMany(),
      prisma.task.deleteMany(),
      prisma.tag.deleteMany(),
      prisma.openProjectTag.deleteMany(),
      prisma.taskStatus.deleteMany(),
      prisma.taskList.deleteMany(),
      prisma.milestone.deleteMany(),
      prisma.document.deleteMany(),
      prisma.spacePermission.deleteMany(),
      prisma.folder.deleteMany(),
      prisma.space.deleteMany(),
      prisma.savedView.deleteMany(),
      prisma.migrationRun.deleteMany(),
      prisma.invite.deleteMany(),
      prisma.membership.deleteMany(),
      prisma.permissionSet.deleteMany(),
      // Delete workspace last — it's the parent of most things.
      // The runtime workspace is recreated by the seed script.
      prisma.workspace.deleteMany(),
    ]);

    const total = counts.reduce((sum, c) => sum + c.count, 0);
    ok(`Deleted ${total} rows across all tables`);
  } finally {
    await prisma.$disconnect();
  }
}

// ─── Hierarchy file ───────────────────────────────────────────────────────────

async function deleteHierarchyFile() {
  step('Deleting seeded hierarchy file');
  try {
    await unlink(seededHierarchyPath());
    ok('clickup-hierarchy.json deleted');
  } catch (error: any) {
    if (error?.code === 'ENOENT') {
      ok('File not found — already clean');
    } else {
      warn(`Could not delete hierarchy file: ${error?.message}`);
    }
  }
}

// ─── Refresh env from .env file ──────────────────────────────────────────────
// setup-openproject may regenerate OPENPROJECT_API_TOKEN and write it to .env.
// Re-read it so subsequent child processes inherit the updated token.

function refreshEnvFromDotenv() {
  const envPath = resolve(dirname(fileURLToPath(import.meta.url)), '../.env');
  try {
    const content = readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const m = line.match(/^([A-Z0-9_]+)="?([^"]*)"?\s*$/);
      if (m) process.env[m[1]] = m[2];
    }
  } catch {
    // .env may not exist in CI — safe to ignore
  }
}

// ─── Run child script ─────────────────────────────────────────────────────────

function runScript(scriptPath: string, label: string) {
  step(label);
  const result = spawnSync('npx', ['tsx', scriptPath], {
    stdio: 'inherit',
    timeout: 600_000,
    env: { ...process.env },
    cwd: resolve(dirname(fileURLToPath(import.meta.url)), '..'),
  });
  if (result.status !== 0) {
    fail(`${label} exited with code ${result.status}`);
  }
  ok(`${label} completed`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs();

  console.log('\n\x1b[1m╔══════════════════════════════════╗\x1b[0m');
  console.log('\x1b[1m║        FULL RESET + RESEED        ║\x1b[0m');
  console.log('\x1b[1m╚══════════════════════════════════╝\x1b[0m');
  console.log(`  Container : ${args.container}`);
  console.log(`  Skip setup: ${args.skipSetup}`);
  console.log(`  Skip seed : ${args.skipSeed}`);

  await nukeOpenProject(args.container);
  await nukePrisma();
  await deleteHierarchyFile();

  if (!args.skipSetup) {
    runScript('scripts/setup-openproject.ts', 'setup-openproject');
    // setup may have written a new API token to .env — refresh process.env before seed
    refreshEnvFromDotenv();
  }

  if (!args.skipSeed) {
    runScript('scripts/seed-openproject-from-clickup.ts', 'seed-openproject-from-clickup');
  }

  console.log('\n\x1b[32m✓ Full reset complete.\x1b[0m\n');
}

void main();
