/**
 * snapshot-openproject.ts
 *
 * Takes a "golden" snapshot of the current OpenProject state (users, groups,
 * roles) and writes it to server/openproject/seed-data/openproject-user-snapshot.json.
 *
 * Run this once whenever the expected state changes (e.g. new users added).
 * The snapshot is then used by `verify:openproject` / `scripts/verify-openproject.ts`
 * to confirm that setup produced the correct result.
 *
 * Usage:
 *   npm run snapshot:openproject
 */
import 'dotenv/config';
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const CONTAINER = process.env.OPENPROJECT_CONTAINER || 'openproject-web-1';
const SNAPSHOT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  '../server/openproject/seed-data/openproject-user-snapshot.json'
);

function step(msg: string) {
  console.log(`\n→ ${msg}`);
}
function ok(msg: string) {
  console.log(`  ✓ ${msg}`);
}
function fail(msg: string) {
  console.error(`  ✗ ${msg}`);
  process.exit(1);
}

function runRails(script: string): string {
  try {
    return execSync(`docker exec -i ${CONTAINER} bundle exec rails runner -`, {
      input: script,
      timeout: 60_000,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
  } catch (err: any) {
    const msg = (err?.stderr || err?.stdout || err?.message || String(err)).slice(0, 500);
    fail(`Rails runner failed: ${msg}`);
    return '';
  }
}

step('Fetching users, groups, and roles from OpenProject…');

const railsScript = `
require 'json'

users = User.where(type: 'User').order(:login).map do |u|
  pw = UserPassword.where(user_id: u.id).last
  {
    login: u.login,
    mail: u.mail,
    admin: u.admin,
    status: u.status,
    force_password_change: u.force_password_change,
    password_type: pw&.type
  }
end

groups = Group.all.order(:name).map do |g|
  {
    name: g.name,
    member_logins: g.users.order(:login).map(&:login)
  }
end

roles = Role.where(builtin: 0).order(:name).map do |r|
  { name: r.name, permissions: r.permissions.map(&:to_s).sort }
end

puts({ users: users, groups: groups, roles: roles }.to_json)
`;

const raw = runRails(railsScript).trim();
// Rails runner may print log lines; the JSON is the last line
const jsonLine = raw
  .split('\n')
  .filter((l) => l.startsWith('{'))
  .at(-1);
if (!jsonLine) fail('Rails runner produced no JSON output');

let parsed: { users: unknown[]; groups: unknown[]; roles: unknown[] };
try {
  parsed = JSON.parse(jsonLine!);
} catch {
  fail('Failed to parse Rails output as JSON');
  process.exit(1);
}

const snapshot = {
  _meta: {
    description:
      'Golden snapshot of OpenProject users, groups, and roles. ' +
      'Generated by scripts/snapshot-openproject.ts. ' +
      'Used by scripts/verify-openproject.ts after setup.',
    adminPassword: process.env.OPENPROJECT_ADMIN_PASSWORD || 'admin',
    userPassword: process.env.OPENPROJECT_IMPORTED_USER_PASSWORD || 'Clickup!2026',
  },
  ...parsed,
};

writeFileSync(SNAPSHOT_PATH, `${JSON.stringify(snapshot, null, 2)}\n`, 'utf8');

ok(
  `Saved snapshot: ${(parsed.users as unknown[]).length} users, ` +
    `${(parsed.groups as unknown[]).length} groups, ` +
    `${(parsed.roles as unknown[]).length} roles`
);
ok(`→ ${SNAPSHOT_PATH}`);
