-- Extend task activity for non-GitHub tracker events.
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_DELETED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_LIST_CHANGED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_PRIORITY_CHANGED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_TITLE_CHANGED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_DESCRIPTION_CHANGED';
ALTER TYPE "ActivityEventType" ADD VALUE IF NOT EXISTS 'TASK_KEY_CHANGED';

ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "previousValue" TEXT;
ALTER TABLE "ActivityLog" ADD COLUMN IF NOT EXISTS "nextValue" TEXT;

CREATE INDEX IF NOT EXISTS "Task_deletedAt_idx" ON "Task"("deletedAt");
